name: Build & Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install packages
        run: |
          python -m pip install --upgrade pip build poetry

      - name: Build a binary wheel and a source tarball
        run: |
          make version
          make build

      - name: Publish build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-package
          path: "./src/**/dist"

  publish-release:
    name: Publish release to PyPI
    needs: [build]
    environment: "prod"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package_path:
          - "sdk"

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: built-package
          path: "./dist"

      - name: List out files
        run: |
          ls -lA ./dist

      - name: List out files
        run: |
          ls -lA ./dist/${{ matrix.package_path }}

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          packages-dir: "./dist/${{ matrix.package_path }}"
          verbose: true