name: Build & Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install packages
        run: |
          python -m pip install --upgrade pip build poetry
          python -m pip install --upgrade --upgrade-strategy eager -e .


      - name: Build a binary wheel and a source tarball
        run: |
          poetry version $(git describe --tags --abbrev=0)
          poetry build

      - name: Publish build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-package
          path: "./dist"

  publish-release:
    name: Publish release to PyPI
    needs: [build]
    environment: "prod"
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: built-package
          path: "./dist"

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          verbose: true

  build-and-publish-docs:
    name: Build and publish docs
    needs: [build, publish-release]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install

      - name: Build docs
        run: |
          poetry run mkdocs build

      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: docs
          folder: site