name: Run examples test

on:
  push:

jobs:
  examples-test:
    name: Examples test
    runs-on: ubuntu-latest
    env:
      ODCAT_AUTH_CLIENT_ID: ${{ secrets.ODCAT_AUTH_CLIENT_ID }}
      ODCAT_AUTH_CLIENT_SECRET: ${{ secrets.ODCAT_AUTH_CLIENT_SECRET }}
      ODCAT_AUTH_AUDIENCE: ${{ secrets.ODCAT_AUTH_AUDIENCE }}
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip build poetry

      - name: Install packages
        run: |
          poetry install

      - name: Add Mask
        run: |
          echo "::add-mask::${{ env.ODCAT_AUTH_CLIENT_ID }}"
          echo "::add-mask::${{ env.ODCAT_AUTH_CLIENT_SECRET }}"
          echo "::add-mask::${{ env.ODCAT_AUTH_AUDIENCE }}"

      - name: Run tests
        run: |
          poetry run pytest tests/test_examples
        env:
          ODCAT_BASE_URL: https://api.hubocean.earth
          GITHUB_SHA: ${{ github.sha }}