name: Run unit tests

on:
  push:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - uses: actions/checkout@v3

      - name: Print current working directory
        run: pwd

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip build poetry

      - name: Install packages
        run: |
          poetry install

      - name: Run tests
        run: |
          poetry run pytest tests/test_unit
